#line 2 "src/lexer.c"

#line 4 "src/lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 113
#define YY_END_OF_BUFFER 114
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[178] =
    {   0,
        0,    0,    0,    0,  114,  112,  111,  110,   91,   85,
       88,   88,   86,  109,   90,   76,   77,   78,   79,   80,
       81,   90,   90,   82,   90,   90,   90,   90,   90,   90,
       90,  108,   93,   92,  113,  111,   88,    0,    0,  109,
       90,   90,   90,   90,   90,   49,   54,   90,   53,   51,
       90,   90,   73,   72,   90,   70,   40,   45,   90,   44,
       42,   90,   90,   90,   90,   90,   90,   90,   90,   83,
       90,   90,   90,   58,   90,   90,   63,   90,   62,   90,
       60,   90,   90,   84,   90,   90,   90,   90,   90,  108,
      107,  103,   99,   98,   94,   95,  100,  101,  102,   96,

      104,  105,  106,   97,   89,   87,   14,   13,   11,   12,
       24,   25,   90,   36,   37,   30,   50,   52,   55,   31,
       56,   23,   20,   22,   74,   19,   21,   39,   41,   43,
       46,   47,    4,   90,    3,    1,    2,   75,   28,   29,
       71,   67,   90,   34,   35,   57,   32,   59,   61,   64,
       65,   33,   17,   18,   90,   90,    5,   38,   15,   16,
       90,   26,   27,   90,   94,   95,   48,    8,    6,   66,
        7,   69,    9,   10,   68,   94,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    1,    1,    1,    1,    5,    1,
        1,    1,    1,    6,    1,    1,    1,    7,    8,    9,
        9,    9,    9,    9,    9,   10,   10,   11,   12,    1,
        1,    1,   13,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   13,   24,   25,   26,   27,   28,
       13,   29,   30,   31,   32,   33,   13,   34,   13,   35,
        1,   36,    1,    1,    1,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   46,   13,   47,   48,   49,
       50,   51,   13,   52,   53,   54,   55,   56,   13,   57,
       13,   58,   59,    1,   59,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[60] =
    {   0,
        1,    1,    2,    3,    1,    1,    4,    4,    4,    4,
        1,    1,    5,    6,    6,    6,    6,    6,    6,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    3,    6,    6,    6,    6,
        6,    6,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    7
    } ;

static const flex_int16_t yy_base[184] =
    {   0,
        0,    0,   57,   59,  110,  414,   81,  414,  414,  414,
       58,   62,  414,    0,    0,   58,    0,  102,   63,   42,
       52,   52,  145,   69,   55,   54,   62,  104,  190,  234,
       90,    0,  414,  414,  287,   78,  115,  125,    0,    0,
        0,   67,  118,  142,  121,    0,  158,  130,  183,    0,
      135,  133,    0,    0,  124,  178,    0,  138,  182,  193,
        0,  162,  153,  191,  189,  201,  216,  236,  216,    0,
      223,  222,  230,    0,  222,  240,    0,  245,  280,  244,
        0,  289,  239,  243,  294,  290,  278,  295,  293,    0,
      414,  414,  414,  414,  337,  341,  414,  414,  414,  414,

      414,  414,  414,  414,  140,    0,    0,    0,    0,    0,
        0,    0,  291,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,  285,  335,    0,    0,    0,    0,    0,    0,
        0,    0,  332,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,  337,  331,  322,    0,    0,    0,
      337,    0,    0,  334,  352,  356,    0,    0,    0,    0,
        0,    0,    0,    0,    0,  360,  414,  381,  388,  390,
      396,  403,  407
    } ;

static const flex_int16_t yy_def[184] =
    {   0,
      177,    1,  178,  178,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  179,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  181,  177,  177,  182,  177,  177,  177,  183,  179,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  181,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,

      177,  177,  177,  177,  177,  183,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  177,  177,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  177,    0,  177,  177,  177,
      177,  177,  177
    } ;

static const flex_int16_t yy_nxt[474] =
    {   0,
        6,    7,    8,    9,    6,   10,   11,   12,   12,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   15,   15,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       15,   15,   15,   31,   15,    6,   16,   17,   18,   19,
       20,   15,   15,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   15,   15,   15,   31,   15,    6,   33,
       34,   33,   34,   54,   37,   37,   37,   37,   37,   37,
       37,   37,   38,   42,   43,   55,   51,   56,   52,   36,
       67,   65,   36,   44,   53,   62,   54,   66,  107,   63,
       68,   39,   35,   69,   35,   38,   42,   43,   55,   51,

       56,   52,   64,   67,   65,   87,   44,   53,   62,  177,
       66,  107,   63,   68,   39,   45,   69,   46,   88,   70,
       89,   37,   37,   37,   37,   64,   47,   48,   87,   49,
       71,  105,  105,  108,  109,   72,   50,  177,   45,  110,
       46,   88,   70,   89,  113,  117,  105,  105,  177,   47,
       48,  122,   49,   71,  125,  111,  108,  109,   72,   50,
       57,  123,  110,  112,  118,  128,  124,  113,  117,   58,
       59,  114,   60,  115,  122,  133,  134,  125,  111,   61,
      177,  177,  177,   57,  123,  116,  112,  118,  128,  124,
      177,  177,   58,   59,  114,   60,  115,  129,  133,  134,

      119,  177,   61,   73,  120,   74,  126,   75,  116,  121,
      131,  127,  135,   76,   77,   78,  130,   79,   80,  132,
      129,  136,  137,  119,   81,  177,   73,  120,   74,  126,
       75,  177,  121,  131,  127,  135,   76,   77,   78,  130,
       79,   80,  132,  138,  136,  137,  141,   81,   82,  139,
      142,  143,  146,  144,   83,  147,  177,  140,  145,  152,
      148,   84,  155,  156,   85,   86,  138,  177,  177,  141,
      177,   82,  139,  142,  143,  146,  144,   83,  147,  149,
      140,  145,  152,  148,   84,  155,  156,   85,   86,   92,
       93,   94,  177,   95,   95,   95,   96,  150,  161,  177,

       97,   98,  149,  153,  159,   99,  151,  157,  162,  158,
      154,  160,  100,  164,  167,  101,  163,  102,  168,  103,
      150,  161,  104,   97,   98,  177,  153,  159,   99,  151,
      157,  162,  158,  154,  160,  100,  164,  167,  101,  163,
      102,  168,  103,  165,  165,  165,  166,  166,  166,  166,
      166,  169,  170,  171,  172,  173,  174,  175,  176,  176,
      176,  166,  166,  166,  166,  166,  166,  166,  166,  166,
      177,  177,  177,  177,  169,  170,  171,  172,  173,  174,
      175,   32,   32,   32,   32,   32,   32,   32,   40,  177,
       40,   40,   40,   40,   41,   41,   90,  177,  177,   90,

       90,   90,   90,   91,   91,   91,   91,   91,   91,   91,
      106,  177,  106,    5,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177
    } ;

static const flex_int16_t yy_chk[474] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    4,    4,   20,   11,   11,   11,   11,   12,   12,
       12,   12,   11,   16,   16,   21,   19,   22,   19,   36,
       26,   25,    7,   16,   19,   24,   20,   25,   42,   24,
       27,   11,    3,   27,    4,   11,   16,   16,   21,   19,

       22,   19,   24,   26,   25,   31,   16,   19,   24,    5,
       25,   42,   24,   27,   11,   18,   27,   18,   31,   28,
       31,   37,   37,   37,   37,   24,   18,   18,   31,   18,
       28,   38,   38,   43,   43,   28,   18,    0,   18,   43,
       18,   31,   28,   31,   45,   48,  105,  105,    0,   18,
       18,   51,   18,   28,   55,   44,   43,   43,   28,   18,
       23,   52,   43,   44,   48,   58,   52,   45,   48,   23,
       23,   47,   23,   47,   51,   62,   63,   55,   44,   23,
        0,    0,    0,   23,   52,   47,   44,   48,   58,   52,
        0,    0,   23,   23,   47,   23,   47,   59,   62,   63,

       49,    0,   23,   29,   49,   29,   56,   29,   47,   49,
       60,   56,   64,   29,   29,   29,   59,   29,   29,   60,
       59,   65,   66,   49,   29,    0,   29,   49,   29,   56,
       29,    0,   49,   60,   56,   64,   29,   29,   29,   59,
       29,   29,   60,   67,   65,   66,   69,   29,   30,   68,
       71,   72,   75,   73,   30,   76,    0,   68,   73,   80,
       78,   30,   83,   84,   30,   30,   67,    0,    0,   69,
        0,   30,   68,   71,   72,   75,   73,   30,   76,   78,
       68,   73,   80,   78,   30,   83,   84,   30,   30,   35,
       35,   35,    0,   35,   35,   35,   35,   79,   87,    0,

       35,   35,   78,   82,   86,   35,   79,   85,   88,   85,
       82,   86,   35,   89,  113,   35,   88,   35,  133,   35,
       79,   87,   35,   35,   35,    0,   82,   86,   35,   79,
       85,   88,   85,   82,   86,   35,   89,  113,   35,   88,
       35,  133,   35,   95,   95,   95,   95,   96,   96,   96,
       96,  134,  143,  155,  156,  157,  161,  164,  165,  165,
      165,  165,  166,  166,  166,  166,  176,  176,  176,  176,
        0,    0,    0,    0,  134,  143,  155,  156,  157,  161,
      164,  178,  178,  178,  178,  178,  178,  178,  179,    0,
      179,  179,  179,  179,  180,  180,  181,    0,    0,  181,

      181,  181,  181,  182,  182,  182,  182,  182,  182,  182,
      183,    0,  183,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177,  177,  177,  177,  177,  177,  177,  177,
      177,  177,  177
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[114] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "grammar/lexer.l"
#define YY_NO_INPUT 1
#line 5 "grammar/lexer.l"
#include <stdlib.h>
#include "parser.h"
int error_line;
#define MAX_STR_CONST 1025
char string_buf[MAX_STR_CONST];
char* string_buf_ptr;
#line 645 "src/lexer.c"

#line 647 "src/lexer.c"

#define INITIAL 0
#define STRING 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 16 "grammar/lexer.l"


#line 866 "src/lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 178 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 414 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 18 "grammar/lexer.l"
{ return MOV;  }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 19 "grammar/lexer.l"
{ return MVI;  }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 20 "grammar/lexer.l"
{ return LXI;  }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 21 "grammar/lexer.l"
{ return LDA;  }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 22 "grammar/lexer.l"
{ return STA;  }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 23 "grammar/lexer.l"
{ return LHLD; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 24 "grammar/lexer.l"
{ return SHLD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 25 "grammar/lexer.l"
{ return LDAX; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 26 "grammar/lexer.l"
{ return STAX; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 27 "grammar/lexer.l"
{ return XCHG; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "grammar/lexer.l"
{ return ADD; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "grammar/lexer.l"
{ return ADI; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "grammar/lexer.l"
{ return ADC; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "grammar/lexer.l"
{ return ACI; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "grammar/lexer.l"
{ return SUB; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "grammar/lexer.l"
{ return SUI; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "grammar/lexer.l"
{ return SBB; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "grammar/lexer.l"
{ return SBI; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "grammar/lexer.l"
{ return INR; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "grammar/lexer.l"
{ return DCR; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "grammar/lexer.l"
{ return INX; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "grammar/lexer.l"
{ return DCX; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "grammar/lexer.l"
{ return DAD; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 43 "grammar/lexer.l"
{ return ANA; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 44 "grammar/lexer.l"
{ return ANI; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 45 "grammar/lexer.l"
{ return XRA; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 46 "grammar/lexer.l"
{ return XRI; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 47 "grammar/lexer.l"
{ return ORA; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 48 "grammar/lexer.l"
{ return ORI; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 49 "grammar/lexer.l"
{ return CMP; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 50 "grammar/lexer.l"
{ return CPI; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 51 "grammar/lexer.l"
{ return RLC; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 52 "grammar/lexer.l"
{ return RRC; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 53 "grammar/lexer.l"
{ return RAL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 54 "grammar/lexer.l"
{ return RAR; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 55 "grammar/lexer.l"
{ return CMA; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 56 "grammar/lexer.l"
{ return CMC; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 57 "grammar/lexer.l"
{ return STC; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "grammar/lexer.l"
{ return JMP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "grammar/lexer.l"
{ return JC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "grammar/lexer.l"
{ return JNC; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "grammar/lexer.l"
{ return JNC; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "grammar/lexer.l"
{ return JNZ; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "grammar/lexer.l"
{ return JP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "grammar/lexer.l"
{ return JM; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "grammar/lexer.l"
{ return JPE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "grammar/lexer.l"
{ return JPO; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "grammar/lexer.l"
{ return CALL; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "grammar/lexer.l"
{ return CC; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "grammar/lexer.l"
{ return CNC; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "grammar/lexer.l"
{ return CZ; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "grammar/lexer.l"
{ return CNZ; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "grammar/lexer.l"
{ return CP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "grammar/lexer.l"
{ return CM; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "grammar/lexer.l"
{ return CPE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "grammar/lexer.l"
{ return CPO; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "grammar/lexer.l"
{ return RET; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "grammar/lexer.l"
{ return RC; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "grammar/lexer.l"
{ return RNC; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 80 "grammar/lexer.l"
{ return RZ; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 81 "grammar/lexer.l"
{ return RNZ; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 82 "grammar/lexer.l"
{ return RP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 83 "grammar/lexer.l"
{ return RM; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 84 "grammar/lexer.l"
{ return RPE; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 85 "grammar/lexer.l"
{ return RPO; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 87 "grammar/lexer.l"
{ return PUSH; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 88 "grammar/lexer.l"
{ return POP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 89 "grammar/lexer.l"
{ return XTHL; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 90 "grammar/lexer.l"
{ return SPHL; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 91 "grammar/lexer.l"
{ return IN; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 92 "grammar/lexer.l"
{ return OUT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 93 "grammar/lexer.l"
{ return EI; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 94 "grammar/lexer.l"
{ return DI; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 95 "grammar/lexer.l"
{ return HLT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 96 "grammar/lexer.l"
{ return NOP; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 98 "grammar/lexer.l"
{ return A; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 99 "grammar/lexer.l"
{ return B; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 100 "grammar/lexer.l"
{ return C; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 101 "grammar/lexer.l"
{ return D; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 102 "grammar/lexer.l"
{ return E; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 103 "grammar/lexer.l"
{ return H; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 104 "grammar/lexer.l"
{ return L; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 105 "grammar/lexer.l"
{ return PC; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 106 "grammar/lexer.l"
{ return SP; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 109 "grammar/lexer.l"
{ return COMMA; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 110 "grammar/lexer.l"
{ return COLON; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 111 "grammar/lexer.l"
{ yylval.int_val = strtol(yytext, NULL, 16); return NUMBER; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 112 "grammar/lexer.l"
{ yylval.int_val = strtol(yytext, NULL, 10); return NUMBER; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 113 "grammar/lexer.l"
{ yylval.int_val = strtol(yytext, NULL, 2); return NUMBER; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 115 "grammar/lexer.l"
{ yylval.string_val = strdup(yytext); return NAME; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 117 "grammar/lexer.l"
{ string_buf_ptr = string_buf; error_line = yylineno; BEGIN(STRING); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 118 "grammar/lexer.l"
{
                                /* saw closing quote - all done */
                                BEGIN(INITIAL);
                                *string_buf_ptr = '\0';
                                yylval.string_val = strdup(string_buf);
                                return STR_CONST;
                        }
	YY_BREAK
case 93:
/* rule 93 can match eol */
YY_RULE_SETUP
#line 126 "grammar/lexer.l"
{
                                /* error - unterminated string constant */
                                fprintf(yyout, "[line %d] Error: missing terminating \" character.\n", error_line);
                                yyterminate();
                        }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 132 "grammar/lexer.l"
{
                                /* octal escape sequence */
                                int result;
                                (void) sscanf(yytext + 1, "%o", &result);
                                if (result > 0xff) {
                                        /* error, constant is out-of-bounds */
                                        yyterminate();
                                }
                                *string_buf_ptr++ = result;
                        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 142 "grammar/lexer.l"
{
                                /* generate error - bad escape sequence */
                                fprintf(yyout, "[line %d] Error: unkown escape sequence '%s'\n", yylineno, yytext);
                                // yyerror("");
                                yyterminate();

                        } 
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 149 "grammar/lexer.l"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 150 "grammar/lexer.l"
*string_buf_ptr++ = '\\';
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "grammar/lexer.l"
*string_buf_ptr++ = '\'';
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "grammar/lexer.l"
*string_buf_ptr++ = '"';
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "grammar/lexer.l"
*string_buf_ptr++ = '\a';
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "grammar/lexer.l"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "grammar/lexer.l"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 156 "grammar/lexer.l"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "grammar/lexer.l"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "grammar/lexer.l"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "grammar/lexer.l"
*string_buf_ptr++ = '\v';
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "grammar/lexer.l"
{ 
                                fprintf(yyout, "[line %d] Error: unkown escape sequence '%s'\n", error_line, yytext); 
                                // yyerror("");
                                yyterminate();
                        }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 165 "grammar/lexer.l"
{
                                char* yptr = yytext;
                                while (*yptr) *string_buf_ptr++ = *yptr++;
                        }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 169 "grammar/lexer.l"
/* eat up one-line comments */
	YY_BREAK
case 110:
/* rule 110 can match eol */
YY_RULE_SETUP
#line 170 "grammar/lexer.l"
{ return EOL; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 171 "grammar/lexer.l"
{ /* eat up whitespace */ }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 172 "grammar/lexer.l"
{ fprintf(stderr, "Unrecognised character %s at line %d\n", yytext, yylineno); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 175 "grammar/lexer.l"
ECHO;
	YY_BREAK
#line 1533 "src/lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 178 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 178 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 177);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 175 "grammar/lexer.l"



